name: Run Azure Load Test (JMeter)
on:
  workflow_dispatch:

jobs:
  run-load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Load Test
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: loadtest/loadtest.config.yaml
          loadTestResource: ${{ vars.LOADTEST_RESOURCE_NAME }}
          resourceGroup: ${{ vars.LOADTEST_RESOURCE_GROUP }}
          # Optional: name your run; if omitted, action generates one
          loadTestRunName: run-${{ github.run_id }}
